name: CI | Unit

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - '**'

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Lint scripts
        run: npm run eslint

      - name: Run tests
        run: npm run test


  ci-unit:
    name: CI | Unit
    needs: run-tests
    runs-on: ubuntu-latest

    steps:

      # IMPORTANT NOTE
      #
      # You can not set a workflow to be status check. The job is. Hence the trickery...

      - name: Done
        run: echo "Done!"
