name: Release stable channel

defaults:
  run:
    shell: bash

on: [workflow_dispatch]

jobs:

  release-stable:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Merge develop to master
        run: |
          git fetch --quiet
          git reset --hard origin/master
          git merge --ff-only --quiet origin/develop

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Publish
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update develop
        run: |
          git push origin master:develop --quiet > /dev/null 2>&1
